ALTER TABLE `Notification`
  MODIFY `type` ENUM(
    'NEW_REPORT',
    'INTERVENTION_ASSIGNED',
    'STATUS_CHANGED',
    'FEEDBACK_REQUEST',
    'AUTO_ASSIGNMENT',
    'NEW_TICKET',
    'TICKET_REPLY',
    'INTERVENTION_PAUSED',
    'EXECUTION_CONFIRMATION_REQUEST',
    'EXECUTION_CONFIRMATION_RESPONSE'
  ) NOT NULL;
