services:
  mysql:
    image: mysql:8.0
    container_name: si-grupa7-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service_interventions
      MYSQL_USER: service_app
      MYSQL_PASSWORD: service_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4
    container_name: si-grupa7-adminer
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
