services:
  mysql:
    image: mysql:8.0
    container_name: si-grupa7-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-service_interventions}
      MYSQL_USER: ${MYSQL_USER:-service_app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-service_app}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql/init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USERNAME:-service_app_admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-service_admin}
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runtime
    container_name: si-grupa7-backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      PORT: 4000
      CORS_ORIGIN: ${PUBLIC_HOST:-http://localhost}:3000
      SOCKET_CORS_ORIGIN: ${PUBLIC_HOST:-http://localhost}:3000
      JWT_SECRET: ${JWT_SECRET:-change-me}
      DATABASE_URL: "mysql://${MYSQL_USER:-service_app}:${MYSQL_PASSWORD:-service_app}@mysql:3306/${MYSQL_DATABASE:-service_interventions}"
      KEYCLOAK_URL: ${KEYCLOAK_URL:-http://keycloak:8080}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-service-system}
      KEYCLOAK_CLIENT_ID:  ${KEYCLOAK_CLIENT_ID:-backend-service}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-runtime
      args:
        NEXT_PUBLIC_API_BASE_URL: ${PUBLIC_HOST:-http://localhost}:4000/api/v1
        NEXT_PUBLIC_SOCKET_URL: ${PUBLIC_HOST:-http://localhost}:4000
    container_name: si-grupa7-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: ${PUBLIC_HOST:-http://localhost}:4000/api/v1
      NEXT_PUBLIC_SOCKET_URL: ${PUBLIC_HOST:-http://localhost}:4000
    ports:
      - "3000:3000"

volumes:
  mysql_data: